version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: 12345
      POSTGRES_DB: 12345
    ports:
      - "5433:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
